package com.wechantloup.gamelistoptimization.ui.theme

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

class Dimensions(
    val spacingXs: Dp,
    val spacingS: Dp,
    val spacingM: Dp,
    val spacingL: Dp,
    val spacingLXl: Dp,
    val spacingXl: Dp,
    val spacingXxl: Dp,
    val roundedCornerSizeM: Dp,
    val roundedCornerSizeS: Dp,
    val roundedCornerSizeXs: Dp,
    val totallyRoundedCorner: Dp,
    val elevationNone: Dp,
    val elevationXxs: Dp,
    val elevationXs: Dp,
    val elevationS: Dp,
    val elevationM: Dp,
    val elevationL: Dp,
    val elevationXl: Dp,
    val elevationXxl: Dp,
    val btnSizeM: Dp,
    val btnSizeS: Dp,
    val btnSizeXs: Dp,
    val btnIconSizeS: Dp,
    val btnIconSizeM: Dp,
    val btnHorizontalPaddingM: Dp,
    val btnVerticalPaddingM: Dp,
    val btnHorizontalPaddingS: Dp,
    val btnHorizontalPaddingXs: Dp,
    val dialogTitleImageHeight: Dp,
)

val defaultDimensions = Dimensions(
    spacingXs = 4.dp,
    spacingS = 8.dp,
    spacingM = 16.dp,
    spacingL = 24.dp,
    spacingLXl = 32.dp,
    spacingXl = 48.dp,
    spacingXxl = 64.dp,
    roundedCornerSizeM = 18.dp,
    roundedCornerSizeS = 14.dp,
    roundedCornerSizeXs = 14.dp,
    totallyRoundedCorner = 32.dp,
    elevationNone = 0.dp,
    elevationXxs = 2.dp,
    elevationXs = 4.dp,
    elevationS = 6.dp,
    elevationM = 8.dp,
    elevationL = 12.dp,
    elevationXl = 16.dp,
    elevationXxl = 24.dp,
    btnSizeM = 48.dp,
    btnSizeS = 40.dp,
    btnSizeXs = 32.dp,
    btnIconSizeS = 16.dp,
    btnIconSizeM = 24.dp,
    btnHorizontalPaddingM = 32.dp,
    btnVerticalPaddingM = 16.dp,
    btnHorizontalPaddingS = 24.dp,
    btnHorizontalPaddingXs = 12.dp,
    dialogTitleImageHeight = 180.dp,
)
